; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = pca10059


[env:nrf52840_mdk]
platform = nordicnrf52
framework = arduino
board = mdk_nrf52840_dongle
build_flags = 
    -DCONFIG_NFCT_PINS_AS_GPIOS
    -DBOARD_MDK_NRF52840_DONGLE

monitor_port = COM6

upload_protocol = nrfutil
upload_port= COM53
upload_speed= 115200

[env:pca10059]
platform = nordicnrf52
framework = arduino
board = pca10059
build_flags = 
    -DCONFIG_NFCT_PINS_AS_GPIOS
    -DBOARD_NRF52840_PCA10059

monitor_port = COM6

upload_protocol = nrfutil
upload_port= COM53
upload_speed= 115200